/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Dominio.principal;



/**
 *
 * @author Usuario
 */
public class formularioPrincipal extends javax.swing.JFrame {

    private principal principal;
    
    public formularioPrincipal(principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAlumnos = new javax.swing.JButton();
        botonInscripciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonAlumnos.setText("Alumnos");
        botonAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlumnosActionPerformed(evt);
            }
        });

        botonInscripciones.setText("Inscripciones");
        botonInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInscripcionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(botonAlumnos)
                .addGap(18, 18, 18)
                .addComponent(botonInscripciones)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAlumnos)
                    .addComponent(botonInscripciones))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlumnosActionPerformed
        formularioAlumnos form = new formularioAlumnos(principal);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_botonAlumnosActionPerformed

    private void botonInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInscripcionesActionPerformed
        formularioInscripcion form = new formularioInscripcion(principal);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_botonInscripcionesActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAlumnos;
    private javax.swing.JButton botonInscripciones;
    // End of variables declaration//GEN-END:variables
}
